#!/bin/bash
function finish {
  kill -9 "$pid"
}
trap finish EXIT

mix run --no-halt --detached &
pid=$!

is_server_up() {
  netstat -lt | grep 4040
  return $?
}

until is_server_up; do
  echo
done

ruby acceptance_tests/acceptance_tests.rb
